### ISSUE TITLE
Finalize order incorrect status

### ISSUE THREAD

**Issue by pskrzypek84** [ppiotr191/intivebackend02#2]
1. When I try to finalize order with more than 10 products I got 200 code status. It should be error.

2. When I try to finalize order with unavailable items I got 200 code status. It should be error.

**Comment by ppiotr191** [comment]
fixed

**Comment by pskrzypek84** [comment]
Data should be validated before any save operation. Now I can rent movies to first unavailable.

**Comment by ppiotr191** [comment]
https://github.com/ppiotr191/intivebackend02/commit/b9ceafe4cfd220d93c74d5a8bf6336231fcca1c4
