### ISSUE TITLE
Removing not existing cart items

### ISSUE THREAD

**Issue by pskrzypek84** [ppiotr191/intivebackend02#3]
If I remove items that are not in cart I got OK status. It is a bad request.

**Comment by ppiotr191** [comment]
fixed

**Comment by pskrzypek84** [comment]
Data should be validated before any remove operation. In yours implementation removing from cart can be partially done.

**Comment by ppiotr191** [comment]
https://github.com/ppiotr191/intivebackend02/commit/9758dd138f18ca1790f890b27fec297a6ab17bef
